/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;

/**
 *
 * @author Studente
 */
public class ConvertitoreOrario extends javax.swing.JFrame {

    /**
     * Creates new form ConvertitoreOrario
     */
    public ConvertitoreOrario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelOre = new javax.swing.JLabel();
        LabelMinuti = new javax.swing.JLabel();
        LabelSecondi = new javax.swing.JLabel();
        TxtfOre = new javax.swing.JTextField();
        TxtfMinuti = new javax.swing.JTextField();
        TxtfSecondi = new javax.swing.JTextField();
        ButtonConvert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelOre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelOre.setText("Inserisci Ore");

        LabelMinuti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelMinuti.setText("Inserisci Minuti");

        LabelSecondi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelSecondi.setText("Inserisci Secondi");

        TxtfOre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvertActionPerformed(evt);
            }
        });

        ButtonConvert.setText("Converti");
        ButtonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelOre)
                    .addComponent(LabelMinuti)
                    .addComponent(LabelSecondi))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtfSecondi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtfMinuti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtfOre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelOre)
                    .addComponent(TxtfOre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMinuti)
                    .addComponent(TxtfMinuti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSecondi)
                    .addComponent(TxtfSecondi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConvertActionPerformed
        if (!TxtfOre.getText().equals(""))
        {
            double ore = Double.parseDouble(TxtfOre.getText());
            TxtfMinuti.setText(Double.toString((ore * 60)));
            TxtfSecondi.setText(Double.toString((ore * 3600)));
            TxtfOre.setText("");
        }
        else if (!TxtfMinuti.getText().equals(""))
        {
            double minuti = Double.parseDouble(TxtfMinuti.getText());
            TxtfOre.setText(Double.toString((minuti / 60)));
            TxtfSecondi.setText(Double.toString((minuti * 60)));
            TxtfMinuti.setText("");
        }
        else if (!TxtfSecondi.getText().equals(""))
        {
            double secondi = Double.parseDouble(TxtfSecondi.getText());
            TxtfMinuti.setText(Double.toString((secondi / 60)));
            TxtfOre.setText(Double.toString((secondi / 3600)));
            TxtfSecondi.setText("");
        }

    }//GEN-LAST:event_ButtonConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertitoreOrario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertitoreOrario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertitoreOrario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertitoreOrario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertitoreOrario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConvert;
    private javax.swing.JLabel LabelMinuti;
    private javax.swing.JLabel LabelOre;
    private javax.swing.JLabel LabelSecondi;
    private javax.swing.JTextField TxtfMinuti;
    private javax.swing.JTextField TxtfOre;
    private javax.swing.JTextField TxtfSecondi;
    // End of variables declaration//GEN-END:variables
}
