/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Studente
 */
public class NumeriPrimi extends javax.swing.JFrame {
    /**
     * Creates new form NumeriPrimi
     */
    public NumeriPrimi() {
        initComponents();
    }

    boolean Primo(int n)
    {
        boolean isPrimo = true;
        int i = 2;
        while (i <= n / 2)
        {
            if ((n % i) == 0) //se il numero e' divisibile per i
            {
                isPrimo = false;
                break;
            }
            i++;
        }
        return isPrimo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPrimi1 = new javax.swing.JLabel();
        TextFieldRange1 = new javax.swing.JTextField();
        LabelPrimi2 = new javax.swing.JLabel();
        TextFieldRange2 = new javax.swing.JTextField();
        ButtonRicerca = new javax.swing.JButton();
        ButtonCancella = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaRisultato = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelPrimi1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelPrimi1.setText("Numeri primi tra");

        LabelPrimi2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelPrimi2.setText("e");

        ButtonRicerca.setText("Ricerca");
        ButtonRicerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRicercaActionPerformed(evt);
            }
        });

        ButtonCancella.setText("Cancella");
        ButtonCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancellaActionPerformed(evt);
            }
        });

        TextAreaRisultato.setColumns(20);
        TextAreaRisultato.setRows(5);
        jScrollPane1.setViewportView(TextAreaRisultato);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonRicerca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonCancella))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelPrimi1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldRange1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelPrimi2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldRange2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPrimi1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldRange1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPrimi2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldRange2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRicerca)
                    .addComponent(ButtonCancella))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRicercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRicercaActionPerformed
        TextAreaRisultato.setText("");
        int numero1 = Integer.parseInt(TextFieldRange1.getText());
        int numero2 = Integer.parseInt(TextFieldRange2.getText());
        for(int i = numero1; i <= numero2 ; i++)
        {
            if (Primo(i))
            {
                TextAreaRisultato.append(i + "\n");
            }
        }
    }//GEN-LAST:event_ButtonRicercaActionPerformed

    private void ButtonCancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancellaActionPerformed
        TextFieldRange1.setText("");
        TextFieldRange2.setText("");
        TextAreaRisultato.setText("");
    }//GEN-LAST:event_ButtonCancellaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumeriPrimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumeriPrimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumeriPrimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumeriPrimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumeriPrimi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancella;
    private javax.swing.JButton ButtonRicerca;
    private javax.swing.JLabel LabelPrimi1;
    private javax.swing.JLabel LabelPrimi2;
    private javax.swing.JTextArea TextAreaRisultato;
    private javax.swing.JTextField TextFieldRange1;
    private javax.swing.JTextField TextFieldRange2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
